FROM python:3.11.0-slim-bullseye

# Install Poetry tool
RUN apt-get update
RUN pip3 install poetry && poetry --version

# Create working directory
WORKDIR /workspaces

# Copy the application source files 
COPY ./controller/src/utils ./src/utils
COPY ./controller/src/main.py ./src/main.py
COPY ./controller/src/ha_interface ./src/ha_interface

# Copy the application config files
COPY ./config/controller ./config

# Copy the dependencies source files 
COPY ./controller/src/poetry.lock ./poetry.lock
COPY ./controller/src/poetry.toml ./poetry.toml
COPY ./controller/src/pyproject.toml ./pyproject.toml
COPY ./controller/src/README.md ./README.md

# Install the dependencies and create a virtual environment
RUN poetry install

# Run the Web server
ENTRYPOINT ["poetry", "run", "python", "./src/main.py"]